name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - ruby-head
          - jruby-head
        gemfile:
          - redis_4_0_x
          - redis_4_1_x
          - redis_4_x
    services:
      redis:
        image: redis
    env:
      REDIS_URL: redis://redis:6379
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle --gemfile gemfiles/${{ matrix.gemfile }}.gemfile
      - run: rake
