name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - ruby-head
          - jruby-head
        gemfile:
          - redis_4_0_x
          - redis_4_1_x
          - redis_4_x
    services:
      redis1:
        image: redis
        ports:
          - 6379:6379
      redis2:
        image: redis
        options: --port 6380
        ports:
          - 6380:6380
      redis3:
        image: redis
        options: --port 6381
        ports:
          - 6381:6381
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle --gemfile gemfiles/${{ matrix.gemfile }}.gemfile
      - run: rake
